spring.application.name=party

#h2: dit is de naam van de database
#mem: Dit staat voor memorty. dit betekent dat de database in het geheugen van je computer leeft
#party:Dit is simpelweg de naam die je aan je database geeft.
spring.datasource.url=jdbc:h2:mem:party
#Dit zijn de inlogggevens. Sa staat voor System Administrator.
spring.datasource.username=sa
spring.datasource.password=
#Dit is een van de handigste instellingen! Elke keer als Java iets vraagt aan de database, zie je de echte sql-code
spring.jpa.show-sql=true
#Zorgt ervoor dat die SQL-code niet op één lange, onleesbare regel staat, maar mooi onder elkaar wordt gezet.
spring.jpa.properties.hibernate.format_sql=true
#Dit zegt:"WAcht even met het vullen van de databse totdat Hibernate(de vertaler) helemaal klaar is met het aanmaken van de tabellen."
#Dit voorkomt foutmeldingen als je straks testdate(zoals een data.sql bestand) wilt inladen.
spring.jpa.defer-datasource-initialization=true